FROM php:7.1-fpm

ENV ACCEPT_EULA=Y

ADD ./sources.list /etc/apt/sources.list

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
        curl \
        libz-dev \
        libpq-dev \
        libssl-dev \
        libmcrypt-dev

### Common ext
RUN docker-php-ext-install -j$(nproc) \
        iconv \
        mcrypt \
        mbstring \
        mysqli \
        zip \
        pdo \
        pdo_mysql

### GD
RUN apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libjpeg-dev \
        libpng12-dev
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

### exif
RUN docker-php-ext-install exif
RUN docker-php-ext-configure exif \
            --enable-exif


# Microsoft SQL Server Prerequisites
# https://laravel-news.com/install-microsoft-sql-drivers-php-7-docker
RUN  apt-get update \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/8/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get install -y --no-install-recommends \
        locales \
        apt-transport-https \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        msodbcsql \
        unixodbc-dev

RUN pecl install sqlsrv pdo_sqlsrv \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv
