services:

  php-fpm:
    build:
      context: .
    volumes:
      - ${LOCAL_DIR}:/var/www/
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/log/:/var/log/fpm-php/
    ports:
      - 9082:9000