services:

  php-fpm:
    build:
      context: .
    volumes:
      - ${LOCAL_DIR}:/var/www/
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/log/:/var/log/fpm-php/
      # - ./.config:/root/.config
      # - ./.config/.zshrc:/root/.zshrc
      # - ./.config:/var/www/.config
      # - ./.config/.zshrc:/var/www/.zshrc
    networks:
      - network-lap53

  httpd:
    image: httpd:alpine
    volumes:
      - ${LOCAL_DIR}:/var/www/
      - ./apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache2/conf/sites/:/usr/local/apache2/conf/sites/
    ports:
      - 8085:80

    networks:
      - network-lap53

networks:
  network-lap53:
    driver: bridge
