FROM php:7.1-fpm

ENV ACCEPT_EULA=Y

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
        curl \
        libz-dev \
        libpq-dev \
        libssl-dev \
        libmcrypt-dev

### Common ext
RUN docker-php-ext-install -j$(nproc) \
        iconv \
        mcrypt \
        mbstring \
        mysqli \
        pdo \
        pdo_mysql

### GD
RUN apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libjpeg-dev \
        libpng12-dev
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

#### mssql, sqlsrv sybase, freetds, dblib

# Microsoft SQL Server Prerequisites
# https://laravel-news.com/install-microsoft-sql-drivers-php-7-docker
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/8/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get install -y --no-install-recommends \
        locales \
        apt-transport-https \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        msodbcsql \
        unixodbc-dev

RUN pecl install sqlsrv pdo_sqlsrv \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv


#### sybase, freetds, dblib
# RUN apt-get -y install freetds-bin freetds-common freetds-dev libsybdb5

# RUN ln -s /usr/lib/x86_64-linux-gnu/libsybdb.a /usr/lib/

# RUN docker-php-ext-install pdo_dblib
# RUN sed -i "/tds version =/c tds version = 8.0" /etc/freetds/freetds.conf
